using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SecretSanta.ApiService.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202609180001_InitialPostgreSql")]
public sealed class InitialPostgreSql : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DO $migration$
            BEGIN
            -- Releases before EF migrations used EnsureCreated. Such databases already
            -- contain the application schema but have no __EFMigrationsHistory entry. Treat
            -- them as the baseline; EF will record this migration after Up completes.
            IF to_regclass('"Users"') IS NULL THEN
            -- Keep an explicit ownership marker so Down can distinguish a schema created by
            -- this migration from a pre-existing schema that was only baselined.
            CREATE TABLE "__SecretSantaMigrationSchema" (
                "MigrationId" text NOT NULL PRIMARY KEY
            );
            INSERT INTO "__SecretSantaMigrationSchema" ("MigrationId")
                VALUES ('202609180001_InitialPostgreSql');

            CREATE TABLE "Users" (
                "UserId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "DisplayName" character varying(100) NOT NULL,
                "NormalizedDisplayName" character varying(100) NOT NULL,
                "RealName" character varying(200),
                "Email" character varying(320),
                "NormalizedEmail" character varying(320),
                "IsAnonymous" boolean NOT NULL,
                "PasswordHash" text
            );
            CREATE UNIQUE INDEX "IX_Users_NormalizedDisplayName" ON "Users" ("NormalizedDisplayName");
            CREATE UNIQUE INDEX "IX_Users_NormalizedEmail" ON "Users" ("NormalizedEmail")
                WHERE "NormalizedEmail" IS NOT NULL AND "NormalizedEmail" <> '';

            CREATE TABLE "Games" (
                "GameId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(200) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "IsDrawn" boolean NOT NULL,
                "CreatorId" integer NOT NULL REFERENCES "Users" ("UserId") ON DELETE RESTRICT,
                "GiftCost" integer NOT NULL
            );
            CREATE INDEX "IX_Games_CreatorId" ON "Games" ("CreatorId");

            CREATE TABLE "UserGames" (
                "UserId" integer NOT NULL REFERENCES "Users" ("UserId") ON DELETE CASCADE,
                "GameId" integer NOT NULL REFERENCES "Games" ("GameId") ON DELETE CASCADE,
                PRIMARY KEY ("UserId", "GameId")
            );
            CREATE INDEX "IX_UserGames_GameId" ON "UserGames" ("GameId");

            CREATE TABLE "Wishes" (
                "WishId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" integer NOT NULL REFERENCES "Users" ("UserId") ON DELETE CASCADE,
                "WishText" character varying(1000) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            CREATE INDEX "IX_Wishes_UserId" ON "Wishes" ("UserId");

            CREATE TABLE "AnonGuestCodes" (
                "CodeId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" integer NOT NULL REFERENCES "Users" ("UserId") ON DELETE CASCADE,
                "AccessCode" character varying(100) NOT NULL,
                "ExpiresAt" timestamp with time zone
            );
            CREATE UNIQUE INDEX "IX_AnonGuestCodes_AccessCode" ON "AnonGuestCodes" ("AccessCode");
            CREATE INDEX "IX_AnonGuestCodes_UserId" ON "AnonGuestCodes" ("UserId");

            CREATE TABLE "DeliveryPoints" (
                "DeliveryPointId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Code" character varying(100) NOT NULL,
                "Description" character varying(500)
            );
            CREATE UNIQUE INDEX "IX_DeliveryPoints_Code" ON "DeliveryPoints" ("Code");

            CREATE TABLE "GameInvites" (
                "GameInviteId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "GameId" integer NOT NULL REFERENCES "Games" ("GameId") ON DELETE CASCADE,
                "Token" character varying(100) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX "IX_GameInvites_GameId" ON "GameInvites" ("GameId");
            CREATE UNIQUE INDEX "IX_GameInvites_Token" ON "GameInvites" ("Token");

            CREATE TABLE "UserGifts" (
                "UserGiftId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "GameId" integer NOT NULL REFERENCES "Games" ("GameId") ON DELETE CASCADE,
                "UserId" integer NOT NULL REFERENCES "Users" ("UserId") ON DELETE CASCADE,
                "GiftName" character varying(300) NOT NULL,
                "DeliveryMethod" character varying(300) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            CREATE INDEX "IX_UserGifts_GameId" ON "UserGifts" ("GameId");
            CREATE INDEX "IX_UserGifts_UserId" ON "UserGifts" ("UserId");

            CREATE TABLE "SantaAssignments" (
                "AssignmentId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "GiverUserId" integer NOT NULL REFERENCES "Users" ("UserId") ON DELETE RESTRICT,
                "ReceiverUserId" integer NOT NULL REFERENCES "Users" ("UserId") ON DELETE RESTRICT,
                "GameId" integer NOT NULL REFERENCES "Games" ("GameId") ON DELETE CASCADE,
                "SelectedGiftId" integer REFERENCES "UserGifts" ("UserGiftId") ON DELETE SET NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX "IX_SantaAssignments_GameId_GiverUserId" ON "SantaAssignments" ("GameId", "GiverUserId");
            CREATE UNIQUE INDEX "IX_SantaAssignments_GameId_ReceiverUserId" ON "SantaAssignments" ("GameId", "ReceiverUserId");
            CREATE INDEX "IX_SantaAssignments_GiverUserId" ON "SantaAssignments" ("GiverUserId");
            CREATE INDEX "IX_SantaAssignments_ReceiverUserId" ON "SantaAssignments" ("ReceiverUserId");
            CREATE INDEX "IX_SantaAssignments_SelectedGiftId" ON "SantaAssignments" ("SelectedGiftId");
            END IF;
            END $migration$;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DO $migration$
            BEGIN
            -- A legacy EnsureCreated database does not have the ownership marker. In that
            -- case this migration only recorded a baseline and must not remove its tables.
            IF EXISTS (
                SELECT 1
                FROM pg_catalog.pg_class AS marker
                JOIN pg_catalog.pg_namespace AS marker_namespace
                    ON marker_namespace.oid = marker.relnamespace
                WHERE marker.relname = '__SecretSantaMigrationSchema'
                    AND marker_namespace.nspname = current_schema()
                    AND marker.relkind IN ('r', 'p')
            ) THEN
                IF EXISTS (
                    SELECT 1
                    FROM "__SecretSantaMigrationSchema"
                    WHERE "MigrationId" = '202609180001_InitialPostgreSql'
                ) THEN
                    DROP TABLE "SantaAssignments";
                    DROP TABLE "AnonGuestCodes";
                    DROP TABLE "DeliveryPoints";
                    DROP TABLE "GameInvites";
                    DROP TABLE "UserGifts";
                    DROP TABLE "Wishes";
                    DROP TABLE "UserGames";
                    DROP TABLE "Games";
                    DROP TABLE "Users";
                    DROP TABLE "__SecretSantaMigrationSchema";
                END IF;
            END IF;
            END $migration$;
            """);
    }
}
